/*
 * ThemeSettingsScreen.h
 *
 *  Created on: Mar 8, 2021
 *      Author: neset
 */

#ifndef TOS_GUI_THEMESETTINGSSCREEN_THEMESETTINGSSCREEN_H_
#define TOS_GUI_THEMESETTINGSSCREEN_THEMESETTINGSSCREEN_H_



#endif /* TOS_GUI_THEMESETTINGSSCREEN_THEMESETTINGSSCREEN_H_ */
